version: "2"
services:
  node:
    container_name: health-site
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 8082:8080
    command: "npm start"    
